# Generated by Django 4.0.2 on 2022-03-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=150)),
                ('item_tag', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
