# Generated by Django 4.0.2 on 2022-04-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('subtext1', models.TextField()),
                ('subtext2', models.TextField()),
                ('icon1', models.CharField(max_length=100)),
                ('icon2', models.CharField(max_length=100)),
                ('icon3', models.CharField(max_length=100)),
                ('icon4', models.CharField(max_length=100)),
                ('icon5', models.CharField(max_length=100)),
            ],
        ),
    ]
