# Generated by Django 4.0.2 on 2022-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_cart_quantity_mycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.TextField()),
                ('item_tag', models.CharField(max_length=100)),
                ('item_version', models.CharField(max_length=50)),
                ('item_filesincluded', models.CharField(max_length=50)),
                ('item_documentation', models.CharField(max_length=50)),
                ('item_license', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=150)),
                ('item_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
