# Generated by Django 4.0.2 on 2022-03-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_checkout_delete_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.AddField(
            model_name='checkout',
            name='productid',
            field=models.IntegerField(null=True),
        ),
    ]
